version: '3.18'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: on-failure

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres

  mongodb:
    container_name: mongo_demo
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: [ 'start-dev' ]
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: {YOUR KEYCLOAK USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: {YOUR KEYCLOAK PASSWOR}


  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: {YOUR RABBITMQ USERNAME}
      RABBITMQ_DEFAULT_PASS: {YOUR RABBITMQ PASSWORD}
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

networks:
  local:
    name: local
    driver: bridge
  rabbitmq:
    name: rabbitmq
    driver: bridge
